# Generated by Django 6.0.1 on 2026-03-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentprofile_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='custom_branch',
            field=models.CharField(blank=True, help_text='Enter your branch if "Other" is selected', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='branch',
            field=models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('ECE', 'Electronics & Communication'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('IT', 'Information Technology'), ('EEE', 'Electrical & Electronics Engineering'), ('OTHER', 'Other (Please specify)')], max_length=50),
        ),
    ]
