# Generated by Django 6.0.1 on 2026-01-31 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_opportunity_min_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='requiredskill',
            name='proficiency_level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=20),
        ),
    ]
