# Generated by Django 6.0.1 on 2026-01-30 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.DecimalField(decimal_places=2, help_text='Annual salary or total package in LPA', max_digits=10)),
                ('position', models.CharField(max_length=100)),
                ('placement_year', models.IntegerField(help_text='Year of placement (e.g., 2024)')),
                ('placement_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_records', to='companies.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_records', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-placement_date'],
                'unique_together': {('student', 'company', 'placement_year')},
            },
        ),
    ]
