# Generated by Django 6.0.1 on 2026-01-30 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('opportunities', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TECHNICAL', 'Technical Round'), ('HR', 'HR Round'), ('MANAGER', 'Manager Round'), ('GROUP_DISCUSSION', 'Group Discussion'), ('FINAL', 'Final Round')], max_length=50)),
                ('order', models.PositiveIntegerField(help_text='Order of the round (1, 2, 3...)')),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_rounds', to='opportunities.opportunity')),
            ],
            options={
                'ordering': ['opportunity', 'order'],
                'unique_together': {('opportunity', 'order')},
            },
        ),
        migrations.CreateModel(
            name='InterviewSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='AVAILABLE', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='interviews.interviewround')),
            ],
            options={
                'ordering': ['round', 'scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewer_name', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('result', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('HOLD', 'Hold'), ('NOT_ATTEMPTED', 'Not Attempted')], default='NOT_ATTEMPTED', max_length=20)),
                ('rating', models.PositiveIntegerField(default=0, help_text='Rating out of 10')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_feedbacks', to='applications.application')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='interviews.interviewround')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('application', 'round')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationSlotAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slot_assignment', to='applications.application')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to='interviews.interviewslot')),
            ],
            options={
                'unique_together': {('application', 'slot')},
            },
        ),
    ]
